name: naveen_job
on:
  schedule:
  - cron: '*/20 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    #  - uses: actions/checkout@v3
      - name: Run a one-line script
        #run: java HelloWorld.java
         run:echo Hello 


