name: naveen_job
on:
  schedule:
  - cron: '*/20 * * * *'

jobs:
cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
  #build:
   # runs-on: ubuntu-latest
    steps:
    #  - uses: actions/checkout@v3
      - name: Run a one-line script
        #run: java HelloWorld.java
        # run:echo Hello 
         run: echo Hello, world!


